# Generated by Django 4.1.3 on 2023-03-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='nos',
            new_name='nbr_passager',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='rem',
        ),
    ]
