# Generated by Django 4.1.3 on 2023-03-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_passager_age_passager_email_passager_numero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passager',
            new_name='Passenger',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='passager',
            new_name='passenger',
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut_paiement',
            field=models.BooleanField(default=False),
        ),
    ]
