# Generated by Django 4.1.3 on 2023-03-27 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_date_reservation_reservation_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='passenger',
        ),
        migrations.AddField(
            model_name='reservation',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.passenger'),
            preserve_default=False,
        ),
    ]
