# Generated by Django 4.1.3 on 2023-03-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_reservation_passenger_reservation_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut_paiement',
            field=models.CharField(default='UNPAID', max_length=10),
        ),
    ]
