# Generated by Django 4.2.1 on 2023-05-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_reservation_statut_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='nombre_de_places',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
